name: Flutter Build Android APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      # Setup Flutter environment
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      # Clean flutter cache
      # - name: Clean flutter cache
      #   run: flutter pub cache clean

      # Fetch dependencies
      - name: Get dependencies
        run: flutter pub get

      # Set namespace name to ar_location_view to fix missing namespace
      # - name: Set namespace in build.gradle
      #   run: |
      #     echo "android { namespace 'com.pie.technology.ar.location.view.ar_location_view' }" >> /opt/hostedtoolcache/flutter/3.22.0-stable/x64/.pub-cache/hosted/pub.dev/ar_location_view-2.0.10/android/build.gradle


      # Build APK
      - name: Build APK
        run: flutter build apk --release

      # Upload Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
